Css layout classes
Mitchelllund/m1-0122-code-solutions pull request #17
Opened 2022-02-08 18:57 UTC by Mitchelllund

![Screenshot 2022-02-08 105503-css-layout-classes](https://user-images.githubusercontent.com/90532731/153056457-365fb685-f307-4217-9f98-3372e97789b7.png)

2022-02-09 03:18 UTC, thebearingedge requested changes

2022-02-09 03:18 UTC, thebearingedge commented on css-layout-classes/index.html
> +        </div>
Since these columns are all 1/4th the width of the row, try making just one class that they can all use.

2022-02-09 03:18 UTC, thebearingedge commented on css-layout-classes/styles.css
> +}
Since these are the same width, try making just one class for them that takes up 1/3rd the width of their parent.

2022-02-10 19:01 UTC, Zhiwutian requested changes
Looking good, some updates are needed!

2022-02-12 00:20 UTC, Zhiwutian approved these changes
👍🏼

2022-02-14 18:09 UTC, merged